# Website settings
url: "https://johannesfung.github.io/"
baseurl: ""

# Internal nav
nav:
  main:
    projects: "/projects"
#    reading: "/reading"

# Bio settings
name: "Johannes Fung"
description: "The home page of Johannes Fung."
thumbnail_path: "profile-photos/jofung.jpg"

# URLs
contact_urls:
  linkedin:
    url: "https://www.linkedin.com/in/johannes-fung-23a020160/"
    label: "LinkedIn"
    icon: "linkedin-square"
  github:
    url: "https://github.com/johannesfung"
    label: "GitHub"
    icon: "github-square"
  email:
    url: "mailto:johannesfung@gmail.com"
    label: "Email"
    value: "johannesfung@gmail.com"
    icon: "envelope-square"

# Jekyll build settings
paginate: 10
paginate_path: "/writing/page:num"
permalink: "/writing/:year/:month/:day/:title/"
sass:
  sass_dir: "/assets/css"
  style: :compressed
highlighter: rouge
timezone: 'America/Los_Angeles'
markdown: kramdown

disqus:
  shortname: Han

# Plugins (GitHub Pages only support a few)
gems:
  - jekyll-redirect-from
  - jekyll-sitemap
  - jekyll-paginate
